#!/bin/sh
exec tail -n +3 $0

menuentry '4.5.5 MemDump Linux' --class arch --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-core repo kernel-true-ad4103fa-d940-47ca-8506-301d8071d467' {
	load_video
	set gfxpayload=keep
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos5  5aed7d91-3dae-4ef7-ab97-fcd438a9309c
	else
	  search --no-floppy --fs-uuid --set=root 
	fi
	echo	'Loading Linux core repo kernel ...'
	linux	/boot/vmlinuz-linux-4.5.5-MemDump-Linux root=UUID=5aed7d91-3dae-4ef7-ab97-fcd438a9309c rw  quiet
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initramfs-linux-4.5.5-MemDump-Linux.img
}
